### ISSUE TITLE
Album detail improvements

### ISSUE THREAD

**Issue by lyarenei** [lyarenei/Medusic#20]
Improvements to album detail screen
- [x] Reduce song row size (#19)
- [x] Number of songs and runtime in footer (#26)
- [x] More by artist (album hstack) (#54)
- [x] Three dots menu in navbar (context options) (#43)
- [x] Remove primary button from navbar (#43)
- [x] Handle multidisc album correctly (#36)
- [x] #63
